// AUTO-GENERATED by scripts/build-catalog.ts — do not edit by hand.
// Source: the client's product Excel (scripts/excel-rows.json). Re-run the
// generator to refresh. Finishes, categories and types live in ./catalog.ts.
import type { Product } from "./catalog";

export const products: Product[] = [
  {
    "slug": "e08ka111",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus jednopólového spínača so skrutkovým upevnením",
      "en": "1 Gang mechanism for 1 way switch with screw fixing",
      "cs": "1-násobný mechanismus jednopólového spínače se šroubovým upevněním"
    },
    "description": {
      "sk": "1-násobný mechanizmus jednopólového spínača so skrutkovým upevnením. Týmto spínačom môžete z jedného miesta zapínať a vypínať svietidlo alebo viacero paralelne zapojených svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for 1 way switch with screw fixing. With this switch, you can switch a lamp or several lamps connected in parallel on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus jednopólového spínače se šroubovým upevněním. Tímto spínačem můžete z jednoho místa zapínat a vypínat svítidlo nebo několik paralelně zapojených svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA111",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    },
    "featured": true
  },
  {
    "slug": "e08ka112",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus striedavého prepínača so skrutkovým upevnením",
      "en": "1 Gang mechanism for 2 way switch with screw fixing",
      "cs": "1-násobný mechanismus střídavého přepínače se šroubovým upevněním"
    },
    "description": {
      "sk": "1-násobný mechanizmus striedavého prepínača so skrutkovým upevnením. Týmto prepínačom môžete z dvoch miest zapínať a vypínať svietidlo alebo viacero paralelne zapojených svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for 2 way switch with screw fixing. With this switch, you can switch a lamp or several lamps connected in parallel on and off from two locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus střídavého přepínače se šroubovým upevněním. Tímto přepínačem můžete ze dvou míst zapínat a vypínat svítidlo nebo několik paralelně zapojených svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA112",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka113",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus krížového prepínača so skrutkovým upevnením",
      "en": "1 Gang mechanism for intermediate switch with screw fixing",
      "cs": "1-násobný mechanismus křížového přepínače se šroubovým upevněním"
    },
    "description": {
      "sk": "1-násobný mechanizmus krížového prepínača so skrutkovým upevnením. Tento krížový prepínač umožňuje ovládať jedno svietidlo z troch alebo viacerých miest. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for intermediate switch with screw fixing. This intermediate switch can be used to operate one lamp from three or more locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus křížového přepínače se šroubovým upevněním. Tento křížový přepínač umožňuje ovládat jedno svítidlo ze tří nebo více míst. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA113",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka211",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "2-násobný mechanizmus jednopólového spínača so skrutkovým upevnením",
      "en": "2 Gang mechanism for 1 way switch with screw fixing",
      "cs": "2-násobný mechanismus jednopólového spínače se šroubovým upevněním"
    },
    "description": {
      "sk": "2-násobný mechanizmus jednopólového spínača so skrutkovým upevnením. Týmto spínačom môžete z jedného miesta zapínať a vypínať viacero svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "2 Gang mechanism for 1 way switch with screw fixing. With this switch, you can switch several lamps on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "2-násobný mechanismus jednopólového spínače se šroubovým upevněním. Tímto spínačem můžete z jednoho místa zapínat a vypínat několik svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA211",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka212",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "2-násobný mechanizmus striedavého prepínača so skrutkovým upevnením",
      "en": "2 Gang mechanism for 2 way switch with screw fixing",
      "cs": "2-násobný mechanismus střídavého přepínače se šroubovým upevněním"
    },
    "description": {
      "sk": "2-násobný mechanizmus striedavého prepínača so skrutkovým upevnením. Týmto prepínačom môžete z dvoch miest zapínať a vypínať viacero svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "2 Gang mechanism for 2 way switch with screw fixing. With this switch, you can switch several lamps on and off from two locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "2-násobný mechanismus střídavého přepínače se šroubovým upevněním. Tímto přepínačem můžete ze dvou míst zapínat a vypínat několik svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA212",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka213",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "2-násobný mechanizmus krížového prepínača so skrutkovým upevnením",
      "en": "2 Gang mechanism for intermediate switch with screw fixing",
      "cs": "2-násobný mechanismus křížového přepínače se šroubovým upevněním"
    },
    "description": {
      "sk": "2-násobný mechanizmus krížového prepínača so skrutkovým upevnením. Tento krížový prepínač umožňuje ovládať dve svietidlá z troch alebo viacerých miest. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "2 Gang mechanism for intermediate switch with screw fixing. This intermediate switch can be used to operate two lamp from three or more locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "2-násobný mechanismus křížového přepínače se šroubovým upevněním. Tento křížový přepínač umožňuje ovládat dvě svítidla ze tří nebo více míst. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA213",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka311",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "3-násobný mechanizmus jednopólového spínača so skrutkovým upevnením",
      "en": "3 Gang mechanism for 1 way switch with screw fixing",
      "cs": "3-násobný mechanismus jednopólového spínače se šroubovým upevněním"
    },
    "description": {
      "sk": "3-násobný mechanizmus jednopólového spínača so skrutkovým upevnením. Týmto spínačom môžete z jedného miesta zapínať a vypínať tri alebo viac paralelne zapojených svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "3 Gang mechanism for 1 way switch with screw fixing. With this switch, you can switch three or more lamps connected in parallel on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "3-násobný mechanismus jednopólového spínače se šroubovým upevněním. Tímto spínačem můžete z jednoho místa zapínat a vypínat tři nebo více paralelně zapojených svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA311",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ka215",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus spínača žalúzií so skrutkovým upevnením",
      "en": "Mechanism for roll-down shutter switch with screw fixing",
      "cs": "Mechanismus žaluziového spínače se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus spínača žalúzií so skrutkovým upevnením. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for roll-down shutter switch with screw fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus žaluziového spínače se šroubovým upevněním. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "E08KA215",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ta108",
    "category": "data-media",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus zásuvky HDMI 2.0a, typ A, 180° 4K Full HD @ 60 Hz 3D, HDR, so skrutkovým upevnením",
      "en": "Mechanism for HDMI 2.0a socket, Type A, 180° 4K Full HD @ 60 Hz 3D, HDR with screw fixing",
      "cs": "Mechanismus zásuvky HDMI 2.0a, typ A, 180° 4K Full HD @ 60 Hz 3D, HDR, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus zásuvky HDMI 2.0a, typ A, 180° 4K Full HD @ 60 Hz 3D, HDR, so skrutkovým upevnením. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for HDMI 2.0a socket, Type A, 180° 4K Full HD @ 60 Hz 3D, HDR with screw fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus zásuvky HDMI 2.0a, typ A, 180° 4K Full HD @ 60 Hz 3D, HDR, se šroubovým upevněním. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 21.9,
    "sku": "E08TA108",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 25,5 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08za103",
    "category": "sockets",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard), so skrutkovým upevnením a clonkami",
      "en": "Mechanism for a socket outlet with pin earthing french standart, screw fixing and shutters",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard), se šroubovým upevněním a clonkami"
    },
    "description": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard), so skrutkovým upevnením a clonkami. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for a socket outlet with pin earthing french standart, screw fixing and shutters. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard), se šroubovým upevněním a clonkami. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 24.9,
    "sku": "E08ZA103",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "16 A",
      "protectionDegree": "ip41 (when used with cover E08ZB104, protection increases to ip44)",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 31,2 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    },
    "featured": true
  },
  {
    "slug": "e08ta229",
    "category": "usb-charging",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus USB nabíjačky, 20 W typ A a typ C, so skrutkovým upevnením",
      "en": "Mechanism for USB charger, 20W type A and type C with screw fixing",
      "cs": "Mechanismus USB nabíječky, 20 W typ A a typ C, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus USB nabíjačky, 20 W typ A a typ C, so skrutkovým upevnením. Tento mechanizmus nabíja jedno alebo dve mobilné zariadenia, ako sú mobilné telefóny, tablety, fotoaparáty, MP3 prehrávače a navigačné zariadenia. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for USB charger, 20W type A and type C with screw fixing.. This mechanism charges one or two mobile devices such as mobile phones, tablets, cameras, MP3 players and navigation devices. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus USB nabíječky, 20 W typ A a typ C, se šroubovým upevněním. Tento mechanismus nabíjí jedno nebo dvě mobilní zařízení, jako jsou mobilní telefony, tablety, fotoaparáty, MP3 přehrávače a navigační zařízení. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 29.9,
    "sku": "E08TA229",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "3,5 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 31,4 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    },
    "featured": true
  },
  {
    "slug": "e08ta102",
    "category": "data-media",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus jednoduchej zásuvky RJ45 CAT 6 / trieda E-8, so skrutkovým upevnením",
      "en": "Mechanism for single RJ45 socket CAT 6 / Class E-8 with screw fixing",
      "cs": "Mechanismus jednoduché zásuvky RJ45 CAT 6 / třída E-8, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus jednoduchej zásuvky RJ45 CAT 6 / trieda E-8, so skrutkovým upevnením. Tento mechanizmus slúži na pripojenie jedného zariadenia do siete pre telefón, Ethernet, IP a PoE+. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for single RJ45 socket CAT 6 / Class E-8 with screw fixing. This mechanism is used to connect a single device to a network for telephone, Ethernet, IP and PoE+. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus jednoduché zásuvky RJ45 CAT 6 / třída E-8, se šroubovým upevněním. Tento mechanismus slouží k připojení jednoho zařízení do sítě pro telefon, Ethernet, IP a PoE+. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 21.9,
    "sku": "E08TA102",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 20,7 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ta222",
    "category": "data-media",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus dvojitej zásuvky RJ45 CAT 6 / trieda E-8, so skrutkovým upevnením",
      "en": "Mechanism for double RJ45 socket CAT 6 / Class E-8 with screw fixing",
      "cs": "Mechanismus dvojité zásuvky RJ45 CAT 6 / třída E-8, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus dvojitej zásuvky RJ45 CAT 6 / trieda E-8, so skrutkovým upevnením. Tento mechanizmus slúži na pripojenie dvoch zariadení do siete pre telefón, Ethernet, IP a PoE+. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for double RJ45 socket CAT 6 / Class E-8 with screw fixing. This mechanism is used to connect two device to a network for telephone, Ethernet, IP and PoE+. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus dvojité zásuvky RJ45 CAT 6 / třída E-8, se šroubovým upevněním. Tento mechanismus slouží k připojení dvou zařízení do sítě pro telefon, Ethernet, IP a PoE+. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 21.9,
    "sku": "E08TA222",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 20,7 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ta230",
    "category": "data-media",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus zásuvky RJ45 CAT.6 / TV (konektor male), trieda E-8 / 0–2400 MHz, so skrutkovým upevnením",
      "en": "Mechanism for RJ45 CAT.6 / TV Male socket, Class E-8 / 0-2400 MHz with screw fixing",
      "cs": "Mechanismus zásuvky RJ45 CAT.6 / TV (konektor male), třída E-8 / 0–2400 MHz, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus zásuvky RJ45 CAT.6 / TV (konektor male), trieda E-8 / 0–2400 MHz, so skrutkovým upevnením. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for RJ45 CAT.6 / TV Male socket, Class E-8 / 0-2400 MHz with screw fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus zásuvky RJ45 CAT.6 / TV (konektor male), třída E-8 / 0–2400 MHz, se šroubovým upevněním. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 21.9,
    "sku": "E08TA230",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 20,7 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08za203",
    "category": "sockets",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus dvojzásuvky s kolíkovým uzemnením (francúzsky štandard), so skrutkovým upevnením a clonkami",
      "en": "Mechanism for a double socket outlet with pin earthings french standart, screw fixing and shutters",
      "cs": "Mechanismus dvojzásuvky s kolíkovým uzemněním (francouzský standard), se šroubovým upevněním a clonkami"
    },
    "description": {
      "sk": "Mechanizmus dvojzásuvky s kolíkovým uzemnením (francúzsky štandard), so skrutkovým upevnením a clonkami. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for a double socket outlet with pin earthings french standart, screw fixing and shutters. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus dvojzásuvky s kolíkovým uzemněním (francouzský standard), se šroubovým upevněním a clonkami. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 24.9,
    "sku": "E08ZA203",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "16 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 27,4 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08da102",
    "category": "dimmers",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus triakového otočného stmievača, 200 W LED, so skrutkovým upevnením",
      "en": "Mechanism for Triac rotary dimmer, 200W LED with screw fixing",
      "cs": "Mechanismus triakového otočného stmívače, 200 W LED, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus triakového otočného stmievača, 200 W LED, so skrutkovým upevnením. Tento stmievač je určený na reguláciu jasu osvetlenia v obytných a komerčných priestoroch. Stmievač využíva fázové riadenie so zostupnou hranou sieťového napätia. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for Triac rotary dimmer, 200W LED with screw fixing. This dimmer is designed for controlling lighting brightness in residential and commercial spaces. This dimmer features a phase-shift control circuit based on the trailing edge of the line voltage. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus triakového otočného stmívače, 200 W LED, se šroubovým upevněním. Tento stmívač je určen k regulaci jasu osvětlení v obytných a komerčních prostorech. Stmívač využívá fázové řízení se sestupnou hranou síťového napětí. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 39.9,
    "sku": "E08DA102",
    "specs": {
      "componentType": "dimmer",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 31,2 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    },
    "featured": true
  },
  {
    "slug": "e08da104",
    "category": "climate",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus elektronického termostatu s externým podlahovým snímačom, AC 230 V, 16 A, so skrutkovým upevnením",
      "en": "Mechanism for electronic thermostat with external floor sensor, AC230V, 16A with screw fixing",
      "cs": "Mechanismus elektronického termostatu s externím podlahovým čidlem, AC 230 V, 16 A, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus elektronického termostatu s externým podlahovým snímačom, AC 230 V, 16 A, so skrutkovým upevnením. Tento termostat je určený na udržiavanie používateľom nastavenej teploty v miestnostiach s podlahovým vykurovaním pomocou externého teplotného snímača. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for electronic thermostat with external floor sensor, AC230V, 16A with screw fixing. This thermostat is designed to maintain a user-set temperature in rooms equipped with underfloor heating systems using an external temperature sensor. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus elektronického termostatu s externím podlahovým čidlem, AC 230 V, 16 A, se šroubovým upevněním. Tento termostat je určen k udržování uživatelem nastavené teploty v místnostech s podlahovým vytápěním pomocí externího teplotního čidla. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 54.9,
    "sku": "E08DA104",
    "specs": {
      "componentType": "thermostat",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 33 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ta236",
    "category": "sockets",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard) a USB nabíjačky, 20 W typ A a typ C, so skrutkovým upevnením",
      "en": "Mechanism for a socket outlet with pin earthing french standart and USB charger, 20W type A and type C with screw fixing",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard) a USB nabíječky, 20 W typ A a typ C, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard) a USB nabíjačky, 20 W typ A a typ C, so skrutkovým upevnením. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for a socket outlet with pin earthing french standart and USB charger, 20W type A and type C with screw fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard) a USB nabíječky, 20 W typ A a typ C, se šroubovým upevněním. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 24.9,
    "sku": "E08TA236",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Screw fixing",
      "nominalCurrent": "16 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 54,2 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ba101",
    "category": "accessories",
    "kind": "mechanism",
    "name": {
      "sk": "Vnútorný modul záslepky",
      "en": "Internal module for blank plate",
      "cs": "Vnitřní modul záslepky"
    },
    "description": {
      "sk": "Vnútorný modul záslepky. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Internal module for blank plate. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Vnitřní modul záslepky. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 7.9,
    "sku": "E08BA101",
    "specs": {
      "componentType": "blank plate",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 20,7 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ba102",
    "category": "accessories",
    "kind": "mechanism",
    "name": {
      "sk": "Vnútorný modul vývodu kábla",
      "en": "Internal module for cable output",
      "cs": "Vnitřní modul kabelového vývodu"
    },
    "description": {
      "sk": "Vnútorný modul vývodu kábla. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Internal module for cable output. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Vnitřní modul kabelového vývodu. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 7.9,
    "sku": "E08BA102",
    "specs": {
      "componentType": "cable output",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 22 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08ta103",
    "category": "data-media",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus jednoduchej TV zásuvky (konektor male), 0–2400 MHz, so skrutkovým upevnením",
      "en": "Mechanism for single TV Male socket, 0-2400 MHz with screw fixing",
      "cs": "Mechanismus jednoduché TV zásuvky (konektor male), 0–2400 MHz, se šroubovým upevněním"
    },
    "description": {
      "sk": "Mechanizmus jednoduchej TV zásuvky (konektor male), 0–2400 MHz, so skrutkovým upevnením. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for single TV Male socket, 0-2400 MHz with screw fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus jednoduché TV zásuvky (konektor male), 0–2400 MHz, se šroubovým upevněním. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 21.9,
    "sku": "E08TA103",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "protectionDegree": "ip20",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 20,7 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka111",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus jednopólového spínača s upevnením príchytkami",
      "en": "1 Gang mechanism for 1 way switch with clips fixing",
      "cs": "1-násobný mechanismus jednopólového spínače s upevněním příchytkami"
    },
    "description": {
      "sk": "1-násobný mechanizmus jednopólového spínača s upevnením príchytkami. Týmto spínačom môžete z jedného miesta zapínať a vypínať svietidlo alebo viacero paralelne zapojených svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for 1 way switch with clips fixing. With this switch, you can switch a lamp or several lamps connected in parallel on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus jednopólového spínače s upevněním příchytkami. Tímto spínačem můžete z jednoho místa zapínat a vypínat svítidlo nebo několik paralelně zapojených svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA111",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka112",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus striedavého prepínača s upevnením príchytkami",
      "en": "1 Gang mechanism for 2 way switch with clips fixing",
      "cs": "1-násobný mechanismus střídavého přepínače s upevněním příchytkami"
    },
    "description": {
      "sk": "1-násobný mechanizmus striedavého prepínača s upevnením príchytkami. Týmto prepínačom môžete z dvoch miest zapínať a vypínať svietidlo alebo viacero paralelne zapojených svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for 2 way switch with clips fixing. With this switch, you can switch a lamp or several lamps connected in parallel on and off from two locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus střídavého přepínače s upevněním příchytkami. Tímto přepínačem můžete ze dvou míst zapínat a vypínat svítidlo nebo několik paralelně zapojených svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA112",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka113",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "1-násobný mechanizmus krížového prepínača s upevnením príchytkami",
      "en": "1 Gang mechanism for intermediate switch with clips fixing",
      "cs": "1-násobný mechanismus křížového přepínače s upevněním příchytkami"
    },
    "description": {
      "sk": "1-násobný mechanizmus krížového prepínača s upevnením príchytkami. Tento krížový prepínač umožňuje ovládať jedno svietidlo z troch alebo viacerých miest. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "1 Gang mechanism for intermediate switch with clips fixing. This intermediate switch can be used to operate one lamp from three or more locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "1-násobný mechanismus křížového přepínače s upevněním příchytkami. Tento křížový přepínač umožňuje ovládat jedno svítidlo ze tří nebo více míst. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA113",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 30,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka211",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "2-násobný mechanizmus jednopólového spínača s upevnením príchytkami",
      "en": "2 Gang mechanism for 1 way switch with clips fixing",
      "cs": "2-násobný mechanismus jednopólového spínače s upevněním příchytkami"
    },
    "description": {
      "sk": "2-násobný mechanizmus jednopólového spínača s upevnením príchytkami. Týmto spínačom môžete z jedného miesta zapínať a vypínať viacero svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "2 Gang mechanism for 1 way switch with clips fixing. With this switch, you can switch several lamps on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "2-násobný mechanismus jednopólového spínače s upevněním příchytkami. Tímto spínačem můžete z jednoho místa zapínat a vypínat několik svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA211",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka212",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "2-násobný mechanizmus striedavého prepínača s upevnením príchytkami",
      "en": "2 Gang mechanism for 2 way switch with clips fixing",
      "cs": "2-násobný mechanismus střídavého přepínače s upevněním příchytkami"
    },
    "description": {
      "sk": "2-násobný mechanizmus striedavého prepínača s upevnením príchytkami. Týmto prepínačom môžete z dvoch miest zapínať a vypínať viacero svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "2 Gang mechanism for 2 way switch with clips fixing. With this switch, you can switch several lamps on and off from two locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "2-násobný mechanismus střídavého přepínače s upevněním příchytkami. Tímto přepínačem můžete ze dvou míst zapínat a vypínat několik svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA212",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka311",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "3-násobný mechanizmus jednopólového spínača s upevnením príchytkami",
      "en": "3 Gang mechanism for 1 way switch with clips fixing",
      "cs": "3-násobný mechanismus jednopólového spínače s upevněním příchytkami"
    },
    "description": {
      "sk": "3-násobný mechanizmus jednopólového spínača s upevnením príchytkami. Týmto spínačom môžete z jedného miesta zapínať a vypínať viacero svietidiel. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "3 Gang mechanism for 1 way switch with clips fixing. With this switch, you can switch several lamps on and off from one locations. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "3-násobný mechanismus jednopólového spínače s upevněním příchytkami. Tímto spínačem můžete z jednoho místa zapínat a vypínat několik svítidel. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA311",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08za103",
    "category": "sockets",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard), s upevnením príchytkami",
      "en": "Mechanism for a socket outlet with pin earthing french standart, with clips fixing",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard), s upevněním příchytkami"
    },
    "description": {
      "sk": "Mechanizmus zásuvky s kolíkovým uzemnením (francúzsky štandard), s upevnením príchytkami a clonkami. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for a socket outlet with pin earthing french standart, with clips fixing. and shutters. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus zásuvky s kolíkovým uzemněním (francouzský standard), s upevněním příchytkami a clonkami. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 24.9,
    "sku": "F08ZA103",
    "specs": {
      "componentType": "socket",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "16 A",
      "protectionDegree": "ip41 (when used with cover E08ZB104, protection increases to ip44)",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 33,4 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "f08ka215",
    "category": "switches",
    "kind": "mechanism",
    "name": {
      "sk": "Mechanizmus spínača žalúzií s upevnením príchytkami",
      "en": "Mechanism for roll-down shutter switch with clips fixing",
      "cs": "Mechanismus žaluziového spínače s upevněním příchytkami"
    },
    "description": {
      "sk": "Mechanizmus spínača žalúzií s upevnením príchytkami. Kryt a rámik vo zvolenej farbe je potrebné objednať samostatne.",
      "en": "Mechanism for roll-down shutter switch with clips fixing. The cover and frame in the colour of your choice must be ordered separately.",
      "cs": "Mechanismus žaluziového spínače s upevněním příchytkami. Kryt a rámeček ve zvolené barvě je nutné objednat samostatně."
    },
    "basePrice": 18.9,
    "sku": "F08KA215",
    "specs": {
      "componentType": "switch",
      "color": "Space gray",
      "connectionMethod": "Clips fixing",
      "nominalCurrent": "10 A",
      "protectionDegree": "ip41",
      "temperatureRange": "from -5 °C to +45 °C",
      "marking": "CE",
      "dimensions": "70,9 × 70,9 × 28,8 mm",
      "advantages": "The thickness of the steel support is 1 mm; steel support galvanized on all sides after cutting, even on the cut edges; the grounding E pole and contact group are made of High Precision Copper Alloy; the thickness of the metal in the contact group is 0.6 mm.",
      "installationType": "Built into the wall (with a mounting box) using a screwdriver with the ability to connect mechanisms in groups of 1-5 horizontally and vertically.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb111",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Klávesa pre 1-násobný mechanizmus jednopólového / striedavého spínača",
      "en": "Button for 1 Gang mechanism for 1 way/2 way switch",
      "cs": "Klávesa pro 1-násobný mechanismus jednopólového / střídavého spínače"
    },
    "description": {
      "sk": "Klávesa pre 1-násobný mechanizmus jednopólového / striedavého spínača. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Button for 1 Gang mechanism for 1 way/2 way switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Klávesa pro 1-násobný mechanismus jednopólového / střídavého spínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB111-GLW",
      "soft-touch-white": "E08KB111-MW",
      "soft-touch-carbon": "E08KB111-FBK",
      "soft-touch-cashmere": "E08KB111-CH",
      "graphite": "E08KB111-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb113",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Klávesa pre 1-násobný mechanizmus krížového prepínača",
      "en": "Button for 1 Gang mechanism intermediate switch",
      "cs": "Klávesa pro 1-násobný mechanismus křížového přepínače"
    },
    "description": {
      "sk": "Klávesa pre 1-násobný mechanizmus krížového prepínača. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Button for 1 Gang mechanism intermediate switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Klávesa pro 1-násobný mechanismus křížového přepínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB113-GLW",
      "soft-touch-white": "E08KB113-MW",
      "soft-touch-carbon": "E08KB113-FBK",
      "soft-touch-cashmere": "E08KB113-CH",
      "graphite": "E08KB113-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb211",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Klávesa pre 2-násobný mechanizmus jednopólového / striedavého spínača",
      "en": "Button for 2 gang mechanism for 1 way/2 way switch",
      "cs": "Klávesa pro 2-násobný mechanismus jednopólového / střídavého spínače"
    },
    "description": {
      "sk": "Klávesa pre 2-násobný mechanizmus jednopólového / striedavého spínača. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Button for 2 gang mechanism for 1 way/2 way switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Klávesa pro 2-násobný mechanismus jednopólového / střídavého spínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB211-GLW",
      "soft-touch-white": "E08KB211-MW",
      "soft-touch-carbon": "E08KB211-FBK",
      "soft-touch-cashmere": "E08KB211-CH",
      "graphite": "E08KB211-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb213",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Klávesa pre 2-násobný mechanizmus krížového prepínača",
      "en": "Button for 2 gang mechanism intermediate switch",
      "cs": "Klávesa pro 2-násobný mechanismus křížového přepínače"
    },
    "description": {
      "sk": "Klávesa pre 2-násobný mechanizmus krížového prepínača. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Button for 2 gang mechanism intermediate switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Klávesa pro 2-násobný mechanismus křížového přepínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB213-GLW",
      "soft-touch-white": "E08KB213-MW",
      "soft-touch-carbon": "E08KB213-FBK",
      "soft-touch-cashmere": "E08KB213-CH",
      "graphite": "E08KB213-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb311",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Klávesa pre 3-násobný mechanizmus jednopólového spínača",
      "en": "Button for 3 gang mechanism for 1 way switch",
      "cs": "Klávesa pro 3-násobný mechanismus jednopólového spínače"
    },
    "description": {
      "sk": "Klávesa pre 3-násobný mechanizmus jednopólového spínača. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Button for 3 gang mechanism for 1 way switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Klávesa pro 3-násobný mechanismus jednopólového spínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB311-GLW",
      "soft-touch-white": "E08KB311-MW",
      "soft-touch-carbon": "E08KB311-FBK",
      "soft-touch-cashmere": "E08KB311-CH",
      "graphite": "E08KB311-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08zb103",
    "category": "sockets",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard)",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard)"
    },
    "description": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard). Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard). Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08ZB103-GLW",
      "soft-touch-white": "E08ZB103-MW",
      "soft-touch-carbon": "E08ZB103-FBK",
      "soft-touch-cashmere": "E08ZB103-CH",
      "graphite": "E08ZB103-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism with a screwdriver after installing the frame.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08tb227",
    "category": "usb-charging",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu USB nabíjačky, 20 W typ A a typ C",
      "en": "Cover for mechanism for USB charger, 20W type A and type C",
      "cs": "Kryt mechanismu USB nabíječky, 20 W typ A a typ C"
    },
    "description": {
      "sk": "Kryt mechanizmu USB nabíjačky, 20 W typ A a typ C. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for USB charger, 20W type A and type C. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu USB nabíječky, 20 W typ A a typ C. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08TB227-GLW",
      "soft-touch-white": "E08TB227-MW",
      "soft-touch-carbon": "E08TB227-FBK",
      "soft-touch-cashmere": "E08TB227-CH",
      "graphite": "E08TB227-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08tb102",
    "category": "data-media",
    "kind": "cover",
    "name": {
      "sk": "Kryt jednoduchého mechanizmu zásuvky RJ45 CAT 6 a mechanizmu zásuvky HDMI 2.0a",
      "en": "Cover for single mechanism for RJ45 CAT 6 socket  and for mechanism HDMI 2.0a socket",
      "cs": "Kryt jednoduchého mechanismu zásuvky RJ45 CAT 6 a mechanismu zásuvky HDMI 2.0a"
    },
    "description": {
      "sk": "Kryt jednoduchého mechanizmu zásuvky RJ45 CAT 6 a mechanizmu zásuvky HDMI 2.0a. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for single mechanism for RJ45 CAT 6 socket  and for mechanism HDMI 2.0a socket. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt jednoduchého mechanismu zásuvky RJ45 CAT 6 a mechanismu zásuvky HDMI 2.0a. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08TB102-GLW",
      "soft-touch-white": "E08TB102-MW",
      "soft-touch-carbon": "E08TB102-FBK",
      "soft-touch-cashmere": "E08TB102-CH",
      "graphite": "E08TB102-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08tb222",
    "category": "data-media",
    "kind": "cover",
    "name": {
      "sk": "Kryt dvojitého mechanizmu zásuvky RJ45 CAT 6 a TV zásuvky (konektor male)",
      "en": "Cover for double mechanism for RJ45 socket CAT 6 and TV Male socket",
      "cs": "Kryt dvojitého mechanismu zásuvky RJ45 CAT 6 a TV zásuvky (konektor male)"
    },
    "description": {
      "sk": "Kryt dvojitého mechanizmu zásuvky RJ45 CAT 6 a TV zásuvky (konektor male). Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for double mechanism for RJ45 socket CAT 6 and TV Male socket. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt dvojitého mechanismu zásuvky RJ45 CAT 6 a TV zásuvky (konektor male). Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08TB222-GLW",
      "soft-touch-white": "E08TB222-MW",
      "soft-touch-carbon": "E08TB222-FBK",
      "soft-touch-cashmere": "E08TB222-CH",
      "graphite": "E08TB222-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08bb101",
    "category": "accessories",
    "kind": "cover",
    "name": {
      "sk": "Kryt vnútorného modulu záslepky",
      "en": "Cover for internal module for blank plate.",
      "cs": "Kryt vnitřního modulu záslepky"
    },
    "description": {
      "sk": "Kryt vnútorného modulu záslepky. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for internal module for blank plate.. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt vnitřního modulu záslepky. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08BB101-GLW",
      "soft-touch-white": "E08BB101-MW",
      "soft-touch-carbon": "E08BB101-FBK",
      "soft-touch-cashmere": "E08BB101-CH",
      "graphite": "E08BB101-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08db102",
    "category": "dimmers",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu triakového otočného stmievača, 200 W LED",
      "en": "Cover for mechanism for Triac rotary dimmer, 200W LED",
      "cs": "Kryt mechanismu triakového otočného stmívače, 200 W LED"
    },
    "description": {
      "sk": "Kryt mechanizmu triakového otočného stmievača, 200 W LED. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for Triac rotary dimmer, 200W LED. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu triakového otočného stmívače, 200 W LED. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08DB102-GLW",
      "soft-touch-white": "E08DB102-MW",
      "soft-touch-carbon": "E08DB102-FBK",
      "soft-touch-cashmere": "E08DB102-CH",
      "graphite": "E08DB102-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08db104",
    "category": "climate",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu elektronického termostatu",
      "en": "Cover for mechanism for electronic thermostat",
      "cs": "Kryt mechanismu elektronického termostatu"
    },
    "description": {
      "sk": "Kryt mechanizmu elektronického termostatu. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for electronic thermostat. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu elektronického termostatu. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08DB104-GLW",
      "soft-touch-white": "E08DB104-MW",
      "soft-touch-carbon": "E08DB104-FBK",
      "soft-touch-cashmere": "E08DB104-CH",
      "graphite": "E08BD104-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08kb215",
    "category": "switches",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu spínača žalúzií",
      "en": "Cover for mechanism for roll-down shutter switch",
      "cs": "Kryt mechanismu žaluziového spínače"
    },
    "description": {
      "sk": "Kryt mechanizmu spínača žalúzií. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for roll-down shutter switch. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu žaluziového spínače. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08KB215-GLW",
      "soft-touch-white": "E08KB215-MW",
      "soft-touch-carbon": "E08KB215-FBK",
      "soft-touch-cashmere": "E08KB215-CH",
      "graphite": "E08KB215-GRF"
    },
    "specs": {
      "componentType": "button",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,5 x 70,5 mm",
      "installationType": "Fixed to the mechanism without using any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08zb203",
    "category": "sockets",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu dvojzásuvky s kolíkovým uzemnením (francúzsky štandard) (rámik nie je potrebný)",
      "en": "Cover for mechanism for a double socket outlet with pin earthings french standart (no frame needed)",
      "cs": "Kryt mechanismu dvojzásuvky s kolíkovým uzemněním (francouzský standard) (rámeček není potřeba)"
    },
    "description": {
      "sk": "Kryt mechanizmu dvojzásuvky s kolíkovým uzemnením (francúzsky štandard) (rámik nie je potrebný). Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for a double socket outlet with pin earthings french standart (no frame needed). Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu dvojzásuvky s kolíkovým uzemněním (francouzský standard) (rámeček není potřeba). Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08ZB203-GLW",
      "soft-touch-white": "E08ZB203-MW",
      "soft-touch-carbon": "E08ZB203-FBK",
      "soft-touch-cashmere": "E08ZB203-CH",
      "graphite": "E08ZB203-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "82 × 120 × 27,5 mm",
      "installationType": "Fixed to the mechanism with a screwdriver without frame.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08bb102",
    "category": "accessories",
    "kind": "cover",
    "name": {
      "sk": "Kryt vnútorného modulu vývodu kábla",
      "en": "Cover for internal module for cable output",
      "cs": "Kryt vnitřního modulu kabelového vývodu"
    },
    "description": {
      "sk": "Kryt vnútorného modulu vývodu kábla. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for internal module for cable output. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt vnitřního modulu kabelového vývodu. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08BB102-GLW",
      "soft-touch-white": "E08BB102-MW",
      "soft-touch-carbon": "E08BB102-FBK",
      "soft-touch-cashmere": "E08BB102-CH",
      "graphite": "E08BB102-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 Х 19,3 mm",
      "installationType": "Fixed to the mechanism without any tools after the frame is installed.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08tb236",
    "category": "sockets",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard) a USB nabíjačky, 20 W typ A a typ C",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart and USB charger, 20W type A and type C",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard) a USB nabíječky, 20 W typ A a typ C"
    },
    "description": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard) a USB nabíjačky, 20 W typ A a typ C. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart and USB charger, 20W type A and type C. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard) a USB nabíječky, 20 W typ A a typ C. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08TB236-GLW",
      "soft-touch-white": "E08TB236-MW",
      "soft-touch-carbon": "E08TB236-FBK",
      "soft-touch-cashmere": "E08TB236-CH",
      "graphite": "E08TB236-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 mm",
      "installationType": "Fixed to the mechanism with a screwdriver after installing the frame.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "e08zb104",
    "category": "sockets",
    "kind": "cover",
    "name": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard), IP44",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart ip44",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard), IP44"
    },
    "description": {
      "sk": "Kryt mechanizmu zásuvky s kolíkovým uzemnením (francúzsky štandard), IP44. Dodáva sa vo zvolenom vyhotovení – objednávajte spolu s príslušným mechanizmom a rámikom.",
      "en": "Cover for mechanism for a socket outlet with pin earthing french standart ip44. Supplied in the finish of your choice — order together with the matching mechanism and frame.",
      "cs": "Kryt mechanismu zásuvky s kolíkovým uzemněním (francouzský standard), IP44. Dodává se ve zvoleném provedení – objednávejte společně s odpovídajícím mechanismem a rámečkem."
    },
    "basePrice": 8.9,
    "variantSkus": {
      "glossy-white": "E08ZB104-GLW",
      "soft-touch-white": "E08ZB104-MW",
      "soft-touch-carbon": "E08ZB104-FBK",
      "soft-touch-cashmere": "E08ZB104-CH",
      "graphite": "E08ZB104-GRF"
    },
    "specs": {
      "componentType": "cover",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "70,8 x 70,8 x 9,5 mm",
      "installationType": "Fixed to the mechanism with a screwdriver after installing the frame.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    }
  },
  {
    "slug": "frame",
    "category": "frames",
    "kind": "frame",
    "name": {
      "sk": "Rámik",
      "en": "Frame",
      "cs": "Rámeček"
    },
    "description": {
      "sk": "Univerzálny rámik pre 1 – 5 mechanizmov, tenký iba 9,5 mm. Nacvakáva sa pred klávesy a kryty, vo zvolenom vyhotovení.",
      "en": "Universal frame for 1–5 mechanisms, just 9.5 mm slim. Click-fixed before the buttons and covers, in the finish of your choice.",
      "cs": "Univerzální rámeček pro 1–5 mechanismů, tenký jen 9,5 mm. Nacvakává se před klávesy a kryty, ve zvoleném provedení."
    },
    "basePrice": 9.9,
    "variantSkus": {
      "1-glossy-white": "E08B186-GLW",
      "2-glossy-white": "E08B286-GLW",
      "3-glossy-white": "E08B386-GLW",
      "4-glossy-white": "E08B486-GLW",
      "5-glossy-white": "E08B586-GLW",
      "1-soft-touch-white": "E08B186-MW",
      "2-soft-touch-white": "E08B286-MW",
      "3-soft-touch-white": "E08B386-MW",
      "4-soft-touch-white": "E08B486-MW",
      "5-soft-touch-white": "E08B586-MW",
      "1-soft-touch-carbon": "E08B186-FBK",
      "2-soft-touch-carbon": "E08B286-FBK",
      "3-soft-touch-carbon": "E08B386-FBK",
      "4-soft-touch-carbon": "E08B486-FBK",
      "5-soft-touch-carbon": "E08B586-FBK",
      "1-soft-touch-cashmere": "E08B186-CH",
      "2-soft-touch-cashmere": "E08B286-CH",
      "3-soft-touch-cashmere": "E08B386-CH",
      "4-soft-touch-cashmere": "E08B486-CH",
      "5-soft-touch-cashmere": "E08B586-CH",
      "1-graphite": "E08B186-GRF",
      "2-graphite": "E08B286-GRF",
      "3-graphite": "E08B386-GRF",
      "4-graphite": "E08B486-GRF",
      "5-graphite": "E08B586-GRF"
    },
    "gangs": [
      1,
      2,
      3,
      4,
      5
    ],
    "specs": {
      "componentType": "frame",
      "temperatureRange": "from -5 °C to +45 °C",
      "dimensions": "82 × 82–366 × 9.5 mm (by gang count)",
      "installationType": "Fixed to the mechanism without using any tools before installing buttons and covers.",
      "fireSafety": "The plastic material used to make the frames, covers, and internal parts of all mechanisms successfully passed hot-wire tests at a temperature of +850 °C. All plastic elements have successfully passed the IK06 impact resistance test."
    },
    "featured": true
  }
];
